# Generated by Django 3.2.11 on 2022-02-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sondage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('res_1', models.CharField(max_length=255)),
                ('res_2', models.CharField(max_length=255)),
                ('res_3', models.CharField(max_length=255)),
                ('count_res_1', models.PositiveIntegerField(default=0)),
                ('count_res_2', models.PositiveIntegerField(default=0)),
                ('count_res_3', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
